server:
  port: 8080

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: secret
  config:
    activate:
      on-profile: MYSQL
---
spring:
  datasource:
    url: jdbc:oracle:thin:@NEWMGDEV.WORLD
    username: os
    password: r2017
  config:
    activate:
      on-profile: ORACLE